services:
  # Aplikasi Go - DEVELOPMENT (pakai Air)
  app-dev:
    container_name: go_app_backend_galon_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8024:8080"
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      - DB_NAME=db_metode_saw_depot
      - DB_HOST=db
      - DB_USER=zayndev
      - DB_PASS=Eren1510_
      - DB_PORT=3306
      - DB_PREFIX=tbl

  # Aplikasi Go - PRODUCTION (pakai binary build)
#  app-prod:
#    container_name: go_app_backend_galon
#    build:
#      context: .
#      dockerfile: Dockerfile.prod
#    ports:
#      - "8025:8080"
#    depends_on:
#      - db
#    restart: always
#    networks:
#      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx_golang_galon
    ports:
      - "8022:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app-dev
    networks:
      - mynetwork
    restart: always

  db:
    image: mysql:5.7
    container_name: db_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_metode_saw_depot
      MYSQL_USER: zayndev
      MYSQL_PASSWORD: Eren1510_
    ports:
      - "3329:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmingalon:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmingalon
    environment:
      - PMA_HOST=db
      - PMA_USER=zayndev
      - PMA_PASSWORD=Eren1510_
    ports:
      - "8027:80"
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
